spring:
  data:
    redis:
      repositories:
        enabled: false

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  timeout: 3s
  database: ${REDIS_DATABASE}
  username: ${REDIS_USERNAME:default}
  password: ${REDIS_PASSWORD:}

messaging:
  subscription-reader:
    read-pause-on-failure-ms: ${SUBSCRIPTION_READER_PAUSE_ON_FAILURE_MS:30000}
    recovery-probe-interval-ms: ${SUBSCRIPTION_READER_RECOVERY_PROBE_INTERVAL_MS:5000}
