spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moamoa?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never
  profiles:
    include:
      - redis
      - mail
      - ai