spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  batch:
    job:
      enabled: false
    jdbc:
      platform: mysql
      initialize-schema: always

batch:
  run-key: ${BATCH_RUN_KEY}

logging:
  level:
    org.springframework.batch: ERROR
    org.springframework.boot.autoconfigure.batch: ERROR
    io.micrometer.prometheus.PrometheusMeterRegistry: ERROR
    io.micrometer.prometheusmetrics.PrometheusMeterRegistry: ERROR
