spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: root
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always  # 로컬용(운영은 never 권장)
  data:
    redis:
      host: localhost
      port: 6379