name: deploy

on:
  push:
    branches: [ "release" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: gradle caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: login docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: clean gradle projects
        run: ./gradlew clean

      - name: build
        run: ./gradlew moamoa-core:core-api:build -x test

      - name: docker build and push to hub
        uses: docker/build-push-action@v3
        with:
          context: ./moamoa-core/core-api
          file: ./moamoa-core/core-api/Dockerfile
          push: true
          tags: wwan13/moamoa-core:prod

      - name: Deploy to home server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_REMOTE_HOST }}
          port: ${{ secrets.HOME_REMOTE_PORT }}
          username: ${{ secrets.HOME_REMOTE_USERNAME }}
          key: ${{ secrets.HOME_REMOTE_PRIVATE_KEY }}
          script: |
            cd ~/dev/infra
            docker compose -f docker/moamoa/docker-compose.moamoa.yml pull
            docker compose -f docker/moamoa/docker-compose.moamoa.yml up -d